### ISSUE TITLE
[SUGGESTION] Recipe Toggles

### ISSUE THREAD

**Issue by Nachtflame** [Tfarcenim/SpikeTraps#1]
Is there any chance you could setup a config for T/F toggles or even just a config for "amount per craft" for your recipes? With no native methods for removing/modifying existing recipes, the ability to config them fore purposes of mod-pack customization would be amazing. Thank you!

**Comment by Tfarcenim** [comment]
datapacks can already customize recipes so no need

**Comment by Nachtflame** [comment]
To be fair, this post originated before is figured out how to properly manage that. :)
