### ISSUE TITLE
[1.14.4] Crash when is done booting. "Colliding entity with block"

### ISSUE THREAD

**Issue by Gbergz** [Tfarcenim/SpikeTraps#2]
**Describe the bug**
Server will start then instantly close upon being online for 15 seconds.

**Forge**: 28.1.107
**MC-Version**: 1.14.4
**Mod-Version**: 1.1

Crash-Report: https://gist.github.com/Gbergz/9b34b964000a08b65cf743ad1058e086

_Any ideas?_

**Comment by Tfarcenim** [comment]
seems to have been fixed on their side.
